image: golang:1.13.5

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/


stages:
  - test
  - build
  - integration-test

test:
  extends: .go-cache
  stage: test
  script:
    - go test clamp-core/executors clamp-core/models clamp-core/services
  only:
    - merge_requests
    - master

build:
  extends: .go-cache
  stage: build
  script:
    - go build
  artifacts:
    paths:
      - ./clamp-core
  only:
    - master

integration-test:
  extends: .go-cache
  stage: integration-test
  script:
    - go test clamp-core/handlers
  only:
    - master
