image: golang:1.13.5

cache:
  paths:
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build
  - integration-test

test:
  stage: test
  script:
    - go test clamp-core/executors clamp-core/models clamp-core/services
  only:
    - merge_requests
    - master

build:
  stage: build
  script:
    - go build
  artifacts:
    paths:
      - ./clamp-core
  only:
    - master

integration-test:
  stage: integration-test
  script:
    - go test clamp-core/handlers
  only:
    - master
