version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.13.15

      - image: circleci/postgres:12.4-postgis-ram
        environment:
          POSTGRES_USER: clamptest
          POSTGRES_DB: clamptest
          POSTGRES_PASSWORD: cl@mpt3st

    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: 
          name: run unit tests
          environment:
            CLAMP_DB_CONNECTION_STR: "host=localhost:5432 user=clamptest dbname=clamptest"
          command: go test clamp-core/executors clamp-core/models clamp-core/services

      - run: 
          name: build and publish docker img
          command: |
            echo $GITHUB_CONTAINER_REGISTRY_TOKEN | docker login https://docker.pkg.github.com -u priyaaank --password-stdin
            docker build -t docker.pkg.github.com/clamp-orchestrator/clamp-core/clamp-core:$CIRCLE_SHA1 .
            docker push docker.pkg.github.com/clamp-orchestrator/clamp-core/clamp-core:$CIRCLE_SHA1
            docker system prune -f -a

workflows:
  version: 2
  build_and_test:
    jobs:
      - build