{
 "title": "Clamp-Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Service Response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average response time by business step",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Time taken" }
   ],
   "targets": [
    {
     "expr": "avg by (step_name) (service_request_with_step_name_time_counter{step_status=\"COMPLETED\", step_name!~\"submit motor claim|submit medical claim\"})",
     "legendFormat": "{{step_name}}"
    }
   ]
  },
  {
   "title": "Claim lifecycle completion time - Excluding manual review",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum by (service_request_id) (service_request_with_step_name_time_counter{step_name!~\"submit motor claim|submit medical claim\"}), 100000)",
     "legendFormat": "{{service_request_id}}"
    }
   ]
  },
  {
   "title": "Average Step Response times",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(sum(service_request_with_step_name_time_counter{step_name=\"user authentication\", step_status=\"COMPLETED\"})/count(service_request_with_step_name_counter{step_name=\"user authentication\", step_status=\"COMPLETED\"}))",
     "legendFormat": "User Authentication"
    },
    {
     "expr": "avg(sum(service_request_with_step_name_time_counter{step_name=\"user authorization\", step_status=\"COMPLETED\"})/count(service_request_with_step_name_counter{step_name=\"user authorization\", step_status=\"COMPLETED\"}))",
     "legendFormat": "User Authorization"
    },
    {
     "expr": "avg(sum(service_request_with_step_name_time_counter{step_name=\"get user details\", step_status=\"COMPLETED\"})/count(service_request_with_step_name_counter{step_name=\"get user details\", step_status=\"COMPLETED\"}))",
     "legendFormat": "Get User Info"
    },
    {
     "expr": "avg(sum(service_request_with_step_name_time_counter{step_name=\"create claim\", step_status=\"COMPLETED\"})/count(service_request_with_step_name_counter{step_name=\"create claim\", step_status=\"COMPLETED\"}))",
     "legendFormat": "Create Claim"
    },
    {
     "expr": "avg(sum(service_request_with_step_name_time_counter{step_name=\"submit motor claim\", step_status=\"COMPLETED\"})/count(service_request_with_step_name_counter{step_name=\"submit motor claim\", step_status=\"COMPLETED\"}))",
     "legendFormat": "Submit Motor Claim"
    },
    {
     "expr": "avg(sum(service_request_with_step_name_time_counter{step_name=\"update approved claim\", step_status=\"COMPLETED\"})/count(service_request_with_step_name_counter{step_name=\"update approved claim\", step_status=\"COMPLETED\"}))",
     "legendFormat": "Approved Claims"
    },
    {
     "expr": "avg(sum(service_request_with_step_name_time_counter{step_name=\"process disbursement\", step_status=\"COMPLETED\"})/count(service_request_with_step_name_counter{step_name=\"process disbursement\", step_status=\"COMPLETED\"}))",
     "legendFormat": "Process Disbursement"
    },
    {
     "expr": "avg(sum(service_request_with_step_name_time_counter{step_name=\"notify approval status\", step_status=\"COMPLETED\"})/count(service_request_with_step_name_counter{step_name=\"notify approval status\", step_status=\"COMPLETED\"}))",
     "legendFormat": "Approval Notification"
    },
    {
     "expr": "avg(sum(service_request_with_step_name_time_counter{step_name=\"notify rejection status\", step_status=\"COMPLETED\"})/count(service_request_with_step_name_counter{step_name=\"notify rejection status\", step_status=\"COMPLETED\"}))",
     "legendFormat": "Rejection Notification"
    },
    {
     "expr": "avg(sum(service_request_with_step_name_time_counter{step_name=\"update reject claim\", step_status=\"COMPLETED\"})/count(service_request_with_step_name_counter{step_name=\"update reject claim\", step_status=\"COMPLETED\"}))",
     "legendFormat": "Rejected Claim"
    },
    {
     "expr": "avg(sum(service_request_with_step_name_time_counter{step_name=\"submit medical claim\", step_status=\"COMPLETED\"})/count(service_request_with_step_name_counter{step_name=\"submit medical claim\", step_status=\"COMPLETED\"}))",
     "legendFormat": "Submit Medical Claim"
    }
   ]
  },
  { "title": "Service statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Claims Created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count (count by (service_request_id) (service_request_with_step_name_time_counter))"
    }
   ]
  },
  {
   "title": "Claims pending review",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(count(service_request_with_step_name_counter{step_name=\"submit motor claim\", step_status=\"STARTED\"}))-(count(service_request_with_step_name_counter{step_name=\"update approved claim\", step_status=\"COMPLETED\"})+(count(service_request_with_step_name_counter{step_name=\"update reject claim\", step_status=\"COMPLETED\"})))"
    }
   ]
  },
  {
   "title": "Claim Type Distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "No of Claim Requests" }
   ],
   "targets": [
    {
     "expr": "sum(service_request_with_step_name_counter{step_name=\"submit motor claim\", step_status=\"STARTED\"})",
     "legendFormat": "Motor Claim - Started"
    },
    {
     "expr": "sum(service_request_with_step_name_counter{step_name=\"submit motor claim\", step_status=\"COMPLETED\"})",
     "legendFormat": "Motor Claim - Completed"
    },
    {
     "expr": "sum(service_request_with_step_name_counter{step_name=\"submit motor claim\", step_status=\"FAILED\"})",
     "legendFormat": "Motor Claim - Failed"
    },
    {
     "expr": "sum(service_request_with_step_name_counter{step_name=\"submit medical claim\", step_status=\"STARTED\"})",
     "legendFormat": "Medical Claim - Started"
    },
    {
     "expr": "sum(service_request_with_step_name_counter{step_name=\"submit medical claim\", step_status=\"COMPLETED\"})",
     "legendFormat": "Medical Claim - Complete"
    },
    {
     "expr": "sum(service_request_with_step_name_counter{step_name=\"submit medical claim\", step_status=\"FAILED\"})",
     "legendFormat": "Medical Claim - Failed"
    }
   ]
  },
  {
   "title": "Approved & Rejected Claims",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(service_request_with_step_name_counter{step_name=\"update approved claim\",step_status=\"COMPLETED\"})",
     "legendFormat": "Approved Claim"
    },
    {
     "expr": "sum(service_request_with_step_name_counter{step_name=\"update reject claim\",step_status=\"COMPLETED\"})",
     "legendFormat": "Rejected Claim"
    }
   ]
  },
  { "title": "Workflow statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Total workflows created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "create_workflow_request_handler_counter"
    }
   ]
  }
 ]
}